### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by oliver890312** [Shrinidhi1/Multiclass-Semantic-Segmentation-for-Road-Surface-Detection#1]
Hello
I am a graduate student who is very interested in this paper, but I can't do the test verification. 
Can you provide the training data set,please?

**Comment by Shrinidhi1** [comment]
Hello,
The data is available [Here](https://lapix.ufsc.br/pesquisas/projeto-veiculo-autonomo/datasets/?lang=en). I have taken "Semantic Segmentation GT" data for my project.
